name: Bug Report
description: File a bug report to help us improve
title: "[BUG]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛
        
  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have read the documentation and troubleshooting guides
          required: true
        - label: I agree to follow this project's Code of Conduct
          required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment are you running?
      options:
        - Local Development
        - Azure Development
        - Azure Staging
        - Azure Production
        - Other (please specify in description)
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: What browser are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Mobile Safari
        - Mobile Chrome
        - Other

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop screenshots here or paste them

  - type: textarea
    id: console-logs
    attributes:
      label: Console Logs
      description: If applicable, add browser console logs or server logs
      placeholder: |
        ```
        Paste console output here
        ```

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might help

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low - Minor issue, workaround available
        - Medium - Moderate impact on functionality
        - High - Major feature broken or security concern
        - Critical - System unusable or data loss
    validations:
      required: true

  - type: checkboxes
    id: affected-areas
    attributes:
      label: Affected Areas
      description: Which parts of the application are affected?
      options:
        - label: Authentication/Login
        - label: Task Management
        - label: Dashboard
        - label: User Management
        - label: API Endpoints
        - label: Database
        - label: Infrastructure
        - label: UI/Frontend
        - label: Performance
